# Generated by Django 5.2.11 on 2026-02-13 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('current_round', models.CharField(blank=True, default='Screening', max_length=100)),
                ('viewed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.applicationfield')),
            ],
        ),
        migrations.CreateModel(
            name='JobDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('allowed_branches', models.CharField(help_text='Comma-separated list of branches (e.g., CSE,ECE)', max_length=500)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('eligible_batches', models.CharField(default='2024', help_text='Comma-separated years (e.g., 2024,2025)', max_length=200)),
                ('ctc', models.DecimalField(decimal_places=2, help_text='CTC in LPA', max_digits=10)),
                ('category', models.CharField(choices=[('NORMAL', 'Normal'), ('DREAM', 'Dream'), ('SUPER_DREAM', 'Super Dream')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('frozen', 'Frozen'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('card_color', models.CharField(blank=True, default='#FFE4D6', max_length=20, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='jobs.jobdrive'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobdrive'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offers/')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='jobs.application')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'student')},
        ),
    ]
