# Generated by Django 5.2.11 on 2026-02-13 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdrive',
            name='allowed_branches',
        ),
        migrations.AddField(
            model_name='jobdrive',
            name='backlogs_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdrive',
            name='cgpa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdrive',
            name='eligible_branches',
            field=models.CharField(default='All', help_text='Comma-separated branches e.g. CSE,ECE', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdrive',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'OFFICER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdrive',
            name='max_backlogs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdrive',
            name='min_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdrive',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
