# Generated by Django 5.2.11 on 2026-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
