# Generated by Django 5.2.11 on 2026-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='card_color',
            field=models.CharField(blank=True, default='#FFE4D6', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_tags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
