# Generated by Django 5.2.11 on 2026-02-13 07:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('active_backlogs', models.IntegerField(default=0)),
                ('history_backlogs', models.IntegerField(default=0)),
                ('academic_verified', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('is_placed', models.BooleanField(default=False)),
                ('highest_package', models.DecimalField(decimal_places=2, default=0.0, help_text='In LPA', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
