# Generated by Django 5.2.11 on 2026-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='active_backlogs',
            new_name='backlogs',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='history_backlogs',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('IT', 'Information Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
