# Generated by Django 5.2.11 on 2026-02-13 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_year', models.IntegerField(default=2024, unique=True)),
                ('min_cgpa_default', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('max_backlogs_allowed', models.IntegerField(default=1)),
                ('dream_offer_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='LPA', max_digits=10)),
                ('super_dream_offer_threshold', models.DecimalField(decimal_places=2, default=10.0, help_text='LPA', max_digits=10)),
                ('max_offers_per_student', models.IntegerField(default=1)),
                ('allow_dream_after_normal', models.BooleanField(default=True)),
                ('allow_super_dream_after_dream', models.BooleanField(default=True)),
                ('freeze_placement_season', models.BooleanField(default=False, help_text='If user checked, all applications are frozen')),
            ],
            options={
                'verbose_name_plural': 'Placement Policies',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
