# Generated by Django 5.2.11 on 2026-02-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OFFICER', 'Placement Officer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
